name: release

on:
  push:
    tags: ["*"]

jobs:
  release-windows-amd64:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v -o myst-launcher.exe .
      env:
        GOARCH: amd64
        GOOS: windows
