name: release

on:
  push:
    tags: ["*"]

jobs:
  release-windows-amd64:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: amd64
          GOOS: windows
          EXTRA_FILES: "LICENSE"